language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qtbase5-dev qt5-qmake qttranslations5-l10n qttools5-dev-tools libmediainfo-dev 

before_script:
  - qmake

script:
  - make clean
  - make

branches:
  only:
    - master

os:
  - linux

